[victims]
victim-1 ansible_host=10.0.0.10 ansible_user=root ansible_password=toor ansible_ssh_common_args='-o StrictHostKeyChecking=no'
victim-2 ansible_host=10.0.0.11 ansible_user=root ansible_password=toor ansible_ssh_common_args='-o StrictHostKeyChecking=no'

[firewall]
firewall ansible_host=10.0.0.1 ansible_user=root ansible_ssh_common_args='-o StrictHostKeyChecking=no'

[all:vars]
ansible_python_interpreter=/usr/bin/python3
